import type { CommandRegistry } from '../command-registry.js';
import { registerStartCommand } from './start.js';
import { registerJoinCommand } from './join.js';
import { registerDealCommand } from './deal.js';
import { registerLeaveCommand } from './leave.js';
import { registerBetActions } from './bet-actions.js';
import { registerStatusCommand } from './status.js';
import { registerCashoutCommand } from './cashout.js';
import { registerHelpCommand } from './help.js';
import { registerAdminCommands } from './admin.js';
import { registerHistoryCommand } from './history.js';
import { registerBanterCommands } from './banter.js';
import { registerRebuyCommand } from './rebuy.js';
import { registerStatsCommand } from './stats.js';
import { registerRulesCommand } from './rules.js';
import { registerStacksCommand } from './standings.js';
import { registerShowCommand } from './show.js';
import { registerTotalbuyinCommand } from './totalbuyin.js';
import { registerGroupstatsCommand } from './groupstats.js';
import { registerSitoutCommands } from './sitout.js';
import { registerFeedbackCommand } from './feedback.js';
import { registerRimCommand } from './rim.js';

export function registerAllCommands(registry: CommandRegistry): void {
  registerStartCommand(registry);
  registerJoinCommand(registry);
  registerDealCommand(registry);
  registerLeaveCommand(registry);
  registerBetActions(registry);
  registerStatusCommand(registry);
  registerCashoutCommand(registry);
  registerHelpCommand(registry);
  registerAdminCommands(registry);
  registerHistoryCommand(registry);
  registerRebuyCommand(registry);
  registerStatsCommand(registry);
  registerRulesCommand(registry);
  registerStacksCommand(registry);
  registerBanterCommands(registry);
  registerShowCommand(registry);
  registerTotalbuyinCommand(registry);
  registerGroupstatsCommand(registry);
  registerSitoutCommands(registry);
  registerFeedbackCommand(registry);
  registerRimCommand(registry);
}
